apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoscrap-app-deployment
  labels:
    app: ecoscrap-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecoscrap-app
  template:
    metadata:
      labels:
        app: ecoscrap-app
    spec:
      containers:
      - name: ecoscrap-app
        image: ecoscrap-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://ecoscrap-db:3306/ecoscrap"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "rootpassword"
      imagePullSecrets:
      - name: myregistrykey  # If pulling image from private registry
