version: '3.8'
services:
  ecoscrap-app:
    image: ecoscrap-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoscrap-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecoscrap
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ecoscrap-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecoscrap
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
