apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecoscrap-db
  labels:
    app: ecoscrap-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecoscrap-db
  template:
    metadata:
      labels:
        app: ecoscrap-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: ecoscrap
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: ecoscrap-db
spec:
  ports:
  - port: 3306
  selector:
    app: ecoscrap-db
  clusterIP: None
